<?php
namespace Toshmatovs;
require_once "otaona.php";
class jon extends otaona
{
    public function tellKidsAboutWedding()
    {
        parent::tellKidsAboutWedding(); // TODO: Change the autogenerated stub
    }
}

$jon = new jon();
$jon->tellKidsAboutWedding();