<?php

namespace Toshmatovs;
include_once "parents.php";

class Children extends Parents
{
    public function marry()
    {
        return parent::throwWedding(); // TODO: Change the autogenerated stub
    }
}

$children = new Children();
echo "Children: " . $children->marry();